version: '2.3'

services:

    brezel:
        volumes:
            - ${BREZEL_HOME}/secrets/:/secrets:ro
        entrypoint: /system/entrypoint.sh
        command:
            - source /system/init-gcr-credentials.sh >/dev/null
            - exec ${SHELL}
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: /secrets/${BREZEL_SA_REGISTRY:-registry}.json
            BOTO_CONFIG: /secrets/${BREZEL_BOTO:-gsutil}.boto
